#############################################################################
# Makefile for building: libhttpdecoder.so.1.0.0
# Generated by qmake (2.01a) (Qt 4.8.4) on: lun. mai 11 23:58:24 2015
# Project:  httpdecoder/httpdecoder.pro
# Template: lib
# Command: /usr/lib/i386-linux-gnu/qt4/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile httpdecoder/httpdecoder.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DHTTPDECODER_LIBRARY -DQT_NO_DEBUG -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -Ihttpdecoder -I/usr/include/qt4/QtCore -I/usr/include/qt4 -I. -Ihttpdecoder -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -shared -Wl,-soname,libhttpdecoder.so.1
LIBS          = $(SUBLIBS)  -L/usr/lib/i386-linux-gnu -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/i386-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = httpdecoder/protocol/inter/http/Httpconsumer.cpp \
		httpdecoder/protocol/http/Httpdecoder.cpp \
		httpdecoder/protocol/inter/http/Httpframe.cpp \
		httpdecoder/protocol/http/Httpparser.cpp \
		httpdecoder/utils/Stringutils.cpp 
OBJECTS       = Httpconsumer.o \
		Httpdecoder.o \
		Httpframe.o \
		Httpparser.o \
		Stringutils.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		httpdecoder/httpdecoder.pro
QMAKE_TARGET  = httpdecoder
DESTDIR       = httpdecoder/release/
TARGET        = libhttpdecoder.so.1.0.0
TARGETA       = httpdecoder/release/libhttpdecoder.a
TARGETD       = libhttpdecoder.so.1.0.0
TARGET0       = libhttpdecoder.so
TARGET1       = libhttpdecoder.so.1
TARGET2       = libhttpdecoder.so.1.0

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile  httpdecoder/release/$(TARGET)

httpdecoder/release/$(TARGET):  $(OBJECTS) $(SUBLIBS) $(OBJCOMP)  
	@$(CHK_DIR_EXISTS) httpdecoder/release/ || $(MKDIR) httpdecoder/release/ 
	-$(DEL_FILE) $(TARGET) $(TARGET0) $(TARGET1) $(TARGET2)
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(LIBS) $(OBJCOMP)
	-ln -s $(TARGET) $(TARGET0)
	-ln -s $(TARGET) $(TARGET1)
	-ln -s $(TARGET) $(TARGET2)
	-$(DEL_FILE) httpdecoder/release/$(TARGET)
	-$(DEL_FILE) httpdecoder/release/$(TARGET0)
	-$(DEL_FILE) httpdecoder/release/$(TARGET1)
	-$(DEL_FILE) httpdecoder/release/$(TARGET2)
	-$(MOVE) $(TARGET) $(TARGET0) $(TARGET1) $(TARGET2) httpdecoder/release/



staticlib: $(TARGETA)

$(TARGETA):  $(OBJECTS) $(OBJCOMP) 
	-$(DEL_FILE) $(TARGETA) 
	$(AR) $(TARGETA) $(OBJECTS)

Makefile: httpdecoder/httpdecoder.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/i386-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile httpdecoder/httpdecoder.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/i386-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile httpdecoder/httpdecoder.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/httpdecoder1.0.0 || $(MKDIR) .tmp/httpdecoder1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/httpdecoder1.0.0/ && $(COPY_FILE) --parents httpdecoder/protocol/inter/http/Httpconsumer.h protocol/http/Httpdecoder.h httpdecoder/protocol/http/Httpdecoder_global.h httpdecoder/protocol/inter/http/Httpframe.h httpdecoder/protocol/http/Httpparser.h httpdecoder/protocol/http/Httpstates.h httpdecoder/protocol/inter/http/IhttpFrame.h httpdecoder/utils/Stringutils.h httpdecoder/protocol/http/HttpDecoder.h httpdecoder/protocol/http/httpconstants.h .tmp/httpdecoder1.0.0/ && $(COPY_FILE) --parents httpdecoder/protocol/inter/http/Httpconsumer.cpp httpdecoder/protocol/http/Httpdecoder.cpp httpdecoder/protocol/inter/http/Httpframe.cpp httpdecoder/protocol/http/Httpparser.cpp httpdecoder/utils/Stringutils.cpp .tmp/httpdecoder1.0.0/ && (cd `dirname .tmp/httpdecoder1.0.0` && $(TAR) httpdecoder1.0.0.tar httpdecoder1.0.0 && $(COMPRESS) httpdecoder1.0.0.tar) && $(MOVE) `dirname .tmp/httpdecoder1.0.0`/httpdecoder1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/httpdecoder1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) httpdecoder/release/$(TARGET) 
	-$(DEL_FILE) httpdecoder/release/$(TARGET0) httpdecoder/release/$(TARGET1) httpdecoder/release/$(TARGET2) $(TARGETA)
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

Httpconsumer.o: httpdecoder/protocol/inter/http/Httpconsumer.cpp httpdecoder/protocol/inter/http/Httpconsumer.h \
		httpdecoder/protocol/inter/http/IhttpFrame.h \
		httpdecoder/protocol/http/Httpparser.h \
		httpdecoder/protocol/http/Httpstates.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Httpconsumer.o httpdecoder/protocol/inter/http/Httpconsumer.cpp

Httpdecoder.o: httpdecoder/protocol/http/Httpdecoder.cpp httpdecoder/protocol/http/HttpDecoder.h \
		httpdecoder/protocol/inter/http/Httpconsumer.h \
		httpdecoder/protocol/inter/http/IhttpFrame.h \
		httpdecoder/protocol/http/httpconstants.h \
		httpdecoder/protocol/http/Httpparser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Httpdecoder.o httpdecoder/protocol/http/Httpdecoder.cpp

Httpframe.o: httpdecoder/protocol/inter/http/Httpframe.cpp httpdecoder/protocol/inter/http/Httpframe.h \
		httpdecoder/protocol/inter/http/IhttpFrame.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Httpframe.o httpdecoder/protocol/inter/http/Httpframe.cpp

Httpparser.o: httpdecoder/protocol/http/Httpparser.cpp httpdecoder/protocol/http/Httpparser.h \
		httpdecoder/protocol/inter/http/Httpconsumer.h \
		httpdecoder/protocol/inter/http/IhttpFrame.h \
		httpdecoder/utils/Stringutils.h \
		httpdecoder/protocol/http/httpconstants.h \
		httpdecoder/protocol/http/Httpstates.h \
		httpdecoder/protocol/inter/http/Httpframe.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Httpparser.o httpdecoder/protocol/http/Httpparser.cpp

Stringutils.o: httpdecoder/utils/Stringutils.cpp httpdecoder/utils/Stringutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Stringutils.o httpdecoder/utils/Stringutils.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/lib/ || $(MKDIR) $(INSTALL_ROOT)/usr/lib/ 
	-$(INSTALL_PROGRAM) "httpdecoder/release/$(TARGET)" "$(INSTALL_ROOT)/usr/lib/$(TARGET)"
	-$(STRIP) --strip-unneeded "$(INSTALL_ROOT)/usr/lib/$(TARGET)"
	-$(SYMLINK) "$(TARGET)" "$(INSTALL_ROOT)/usr/lib/$(TARGET0)"
	-$(SYMLINK) "$(TARGET)" "$(INSTALL_ROOT)/usr/lib/$(TARGET1)"
	-$(SYMLINK) "$(TARGET)" "$(INSTALL_ROOT)/usr/lib/$(TARGET2)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/usr/lib/$(TARGET)" 
	 -$(DEL_FILE) "$(INSTALL_ROOT)/usr/lib/$(TARGET0)" 
	 -$(DEL_FILE) "$(INSTALL_ROOT)/usr/lib/$(TARGET1)" 
	 -$(DEL_FILE) "$(INSTALL_ROOT)/usr/lib/$(TARGET2)"
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/lib/ 


install:  install_target  FORCE

uninstall: uninstall_target   FORCE

FORCE:

